server:
  port: 8080

spring:
#    freemarker:
#      suffix: .ftl
#      charset: utf-8
#      cache: false
#      content-type: text/html
    datasource:
        name: lym
        url: jdbc:mysql://192.168.199.178:3306/lym
        username: root
        password: liaoyumiao
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lym.manager.model

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql